name: ech_canary
description: ECH Canary — 可解释的网络可达性与 ECH 绕过诊断。
publish_to: none
version: 1.0.0+10000

environment:
  sdk: ^3.13.0
  flutter: '>=3.47.0'

dependencies:
  flutter:
    sdk: flutter
  ech_http: ^0.2.0
  http: ^1.6.0
  material_ui: ^1.4.0
  material_3_expressive: ^1.1.3
  shared_preferences: ^2.5.5
  path_provider: ^2.1.6
  file_selector: ^1.1.0
  share_plus: ^13.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
